name: CI
on:
   push:
      branches: ["main"]

jobs:
    basic:
      runs-on: ubuntu-latest
      steps:
         - name: print a normal statement
           run: echo "don't loose hope"
           
